# Some of our actions will require build essentials.
- name: PHP | PHP core and required modules
  action: apt pkg={{ item }} state=installed
  notify: restart {{ service }}
  tags: php
  with_items:
    - php5
    - php5-curl
    - php5-cli
    - php5-dev
    - php5-fpm
    - php5-mcrypt
    - php5-mysql
