# Some of our actions will require build essentials.
- name: PHP | PHP core and required modules
  apt:
    pkg: "{{ item }}"
    state: installed
  tags: php
  with_items:
    - php5
    - php5-curl
    - php5-cli
    - php5-dev
    - php5-fpm
    - php5-mcrypt
  register: result

# Let's make it easier for our selves.
- name: PHP | Change php user to vagrant
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf
    regexp='^(?:#[^\n]+\n)*user = www-data[^<]+?'
    line='user = vagrant'
    backup=yes
    state=present
    backrefs=yes
- name: PHP | ... and the group
  lineinfile: dest=/etc/php5/fpm/pool.d/www.conf
    regexp='^(?:#[^\n]+\n)*group = www-data[^<]+?'
    line='group = vagrant'
    backup=yes
    state=present
    backrefs=yes

# Restart the service.
- name: PHP | Restart Service after PHP installation.
  service:
    name: "{{ service }}"
    state: restarted
  when: result|changed