# Some of our actions will require build essentials.
- name: PHP | PHP core and required modules
  apt:
    pkg: "{{ item }}"
    state: installed
  tags: php
  with_items:
    - php5
    - php5-curl
    - php5-cli
    - php5-dev
    - php5-fpm
    - php5-mcrypt
  register: result

# Restart the service.
- name: PHP | Restart Service after PHP installation.
  service:
    name: "{{ service }}"
    state: restarted
  when: result|success and not result|skipped